name: Graham Roberts Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8955324743874371
title: Graham Roberts Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.905991603853181
  lightness: 0.41592504712753
  saturation: 0.4331959974952042
  rhythmicContrast: 0.6463182780425996
purpose: []
