name: Graham Roberts Photography
favicon: null
layout_spectrum: 0.74834
typography_spectrum: 0.8955324743874371
title: Graham Roberts Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#452814'
    - '#985e34'
    - '#ffffff'
    - '#000000'
    - '#e4a48e'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
